name: Deploy Website

on:
  push:
    branches:
      - main # Or your default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your project's Node.js version
          cache: 'npm' # Or 'yarn', 'pnpm'

      - name: Install dependencies
        run: npm install # Or yarn install, pnpm install

      - name: Build project
        run: npm run build # Your build script from package.json
        # Ensure your build outputs to a folder like '.next' for Next.js

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './.next' # Changed to ./.next for Next.js builds

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
